"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. 
Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, 
they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes 
throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""
import random

def cowsAndBullsCheck(randNumb, choiceParam):
	randNumbValues = list(str(randNumb))
	choiceValues = list(str(choiceParam))
	results = {
		'cows': 0,
		'bulls': 0
	}

	print(choiceValues)
	print(randNumbValues)
	
	for index in range(len(randNumbValues)):
		if choiceValues[index] == randNumbValues[index]:
			results['cows'] += 1
		elif choiceValues[index] in randNumbValues:
			results['bulls'] += 1
	return results

def cowsAndBullsGame():
	randomNumber = random.randint(1000, 9999)
	game = True

	while(game):
		choice = input('What do you think the 4-digit number is? ')
		if choice.isdigit() and len(str(choice)) == 4:
			result = cowsAndBullsCheck(randomNumber, int(choice))
			if result['cows'] == 4:
				print(result)
				print('You win!')
				game = False
			else:
				print(result)
		else:
			print('invalid input')

if __name__ == '__main__':
	cowsAndBullsGame()